---

- name: Ansible Playbook for configuring Raspbian Lite distribution
  hosts: fruitpi
  roles:
     - core
     - createuser
     - securessh
     - firewall
     - nginx
    # Use only if You're sure You will finish provisioning
    # - securepi
  vars:
    user: gabor
    group: staff

  remote_user: pi
  sudo: yes
