---
- name: "Update APT package cache"
  action: apt update_cache=yes

- name: "Upgrade APT to the lastest packages"
  action: apt upgrade=safe

- name: "Set hostname to {{ hostname }}"
  hostname: name={{ hostname }}

- name: "Fix /etc/hosts raspberrypi -> {{ hostname }}"
  lineinfile: dest=/etc/hosts regexp="^127.0.1.1" line="127.0.1.1 {{ hostname }}"

- name: "Install unattended-upgrades"
  apt: name=unattended-upgrades state=present

- name: "Configure unattended-upgrades"
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="^//\s+\"o=Raspbian,a=stable\";" line="        \"o=Raspbian,a=stable\";"

- name: "Enable unattended-upgrades"
  shell: echo "APT::Periodic::Update-Package-Lists \"1\";\nAPT::Periodic::Unattended-Upgrade \"1\";" > /etc/apt/apt.conf.d/20auto-upgrades

- name: "Disable WiFi and Bluetooth"
  shell: echo "#WiFi\nblacklist brcmfmac\nblacklist brcmutil\n\n#Bluetooth\nblacklist btbcm\nblacklist hci_uart" > /etc/modprobe.d/raspi-blacklist.conf && modprobe -r -v brcmfmac

- name: "Turn off HDMI"
  shell: tvservice -o
